resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

packages:
  - '.'

extra-deps:
  - dependent-sum-template-0.0.0.6
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - zenc-0.1.1
  - jsaddle-0.9.3.0
  - matrices-0.4.5
  - optparse-applicative-0.14.0.0
  - '../common'
  - 'reflex-dom-semui'

  - git: https://github.com/ghcjs/ghcjs-dom.git
    commit: b6266a1df2029e1c295ad04d6a33a93c7eff0f1c 
    subdirs:
      - ghcjs-dom
      - ghcjs-dom-jsffi
#      - ghcjs-dom-jsaddle

  - git: https://github.com/reflex-frp/reflex.git
    commit: 15c99fc6adf4926289d12c0e19fa96b9b1a1e731

  - git: https://github.com/reflex-frp/reflex-dom.git
    commit: 8bde2d72193369c92a995820ca1f56690d3c8ec3
    subdirs:
      - reflex-dom-core
      - reflex-dom

  - git: https://github.com/reflex-frp/reflex-dom-contrib.git
    commit: 10818e345c4cb34c6a1282add2c26e05c6007ad6

  - git: https://github.com/kaizhang/SciFlow.git
    commit: e68c9b4d24ab766a8e2137e8f4e6f632dd7cc1a9

  - git: https://github.com/Taiji-pipeline/Taiji-types.git
    commit: 61f13cc6f4d63b9ce3712710dcdd716c19aba487


