resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

packages:
  - '.'
  - '../common'
  - 'reflex-dom-semui'
  - location:
      git: https://github.com/ghcjs/ghcjs-dom.git
      commit: "b5984c8326f6eb1e29f2ca60c0e88eb6ecfdc0c1"
    subdirs:
      - ghcjs-dom
      - ghcjs-dom-jsffi
#      - ghcjs-dom-jsaddle

  - location:
      git: https://github.com/reflex-frp/reflex.git
      commit: 1d3a26b3f7d7d50cfe95bb3a28eca38981ad9ec3

  - location:
      git: https://github.com/reflex-frp/reflex-dom.git
      commit: 275939f650b87d2d46b6b8416655d963fee9280e
    subdirs:
      - reflex-dom-core
      - reflex-dom

  - location:
      git: https://github.com/reflex-frp/reflex-dom-contrib.git
      commit: 57eeca60e5f2d579bd202e4af40c430bebd0f853

  - location:
      git: https://github.com/kaizhang/SciFlow.git
      commit: 81e0649f83f56257654d0ddb2602837549b5fc89

extra-deps:
  - dependent-sum-template-0.0.0.6
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - zenc-0.1.1
  - jsaddle-0.9.3.0
  - matrices-0.4.5
