resolver: lts-9.1

packages:
- '.'

- '../common'

- location:
    git: https://github.com/kaizhang/SciFlow.git
    commit: b9f4926a65894f4dc016b364dbef68436d6db86e

- location:
    git: https://github.com/Taiji-pipeline/Taiji-types.git
    commit: 61f13cc6f4d63b9ce3712710dcdd716c19aba487

extra-deps:
  - cereal-vector-0.2.0.1
  - optparse-applicative-0.14.0.0
