resolver: lts-8.22

packages:
- '.'
- '../common'
- location:
    git: https://github.com/kaizhang/SciFlow.git
    commit: b9f4926a65894f4dc016b364dbef68436d6db86e

extra-deps:
  - optparse-applicative-0.14.0.0
